"""Initial migration

Revision ID: 7fa756f55b80
Revises: 
Create Date: 2026-08-05 20:54:49.800748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa756f55b80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_statistics',
    sa.Column('total_waste', sa.Float(), nullable=True),
    sa.Column('total_compost', sa.Float(), nullable=True),
    sa.Column('total_biogas', sa.Float(), nullable=True),
    sa.Column('total_donations', sa.Float(), nullable=True),
    sa.Column('carbon_saved', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_statistics_id'), 'dashboard_statistics', ['id'], unique=False)
    op.create_table('food_waste_logs',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('food_category', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('people_served', sa.Integer(), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('special_event', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_waste_logs_date'), 'food_waste_logs', ['date'], unique=False)
    op.create_index(op.f('ix_food_waste_logs_id'), 'food_waste_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'viewer', name='userrole'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('recovery_recommendations',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_method', sa.String(length=100), nullable=False),
    sa.Column('expected_output', sa.Float(), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['food_waste_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_recommendations_id'), 'recovery_recommendations', ['id'], unique=False)
    op.create_table('waste_predictions',
    sa.Column('log_id', sa.String(length=36), nullable=True),
    sa.Column('predicted_quantity', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['food_waste_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_predictions_id'), 'waste_predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_predictions_id'), table_name='waste_predictions')
    op.drop_table('waste_predictions')
    op.drop_index(op.f('ix_recovery_recommendations_id'), table_name='recovery_recommendations')
    op.drop_table('recovery_recommendations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_food_waste_logs_id'), table_name='food_waste_logs')
    op.drop_index(op.f('ix_food_waste_logs_date'), table_name='food_waste_logs')
    op.drop_table('food_waste_logs')
    op.drop_index(op.f('ix_dashboard_statistics_id'), table_name='dashboard_statistics')
    op.drop_table('dashboard_statistics')
    # ### end Alembic commands ###
