"""Add ImageMetadata table

Revision ID: dcf6f087e669
Revises: 7fa756f55b80
Create Date: 2026-08-05 22:51:18.622690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf6f087e669'
down_revision: Union[str, Sequence[str], None] = '7fa756f55b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_metadata',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('result_filename', sa.String(length=255), nullable=True),
    sa.Column('detected_categories', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_metadata_id'), 'image_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_metadata_id'), table_name='image_metadata')
    op.drop_table('image_metadata')
    # ### end Alembic commands ###
